In [1]:
from neuralnet.second_version import *
import numpy as np
from numpy import ndarray

In [2]:
def assert_same_shape(A: ndarray, B:ndarray):
    assert A.shape == B.shape
    
def assert_dim(X: ndarray, dim: ndarray):
    assert len(X.shape) == dim

In [3]:
input_1d = np.array([1,2,3,4,5])
param_1d = np.array([1,1,1])

In [6]:
def _pad_1d(input_: ndarray, padding: int) -> ndarray:
    zero = np.array([0])
    zero = np.repeat(zero, padding)
    return np.concatenate([zero,input_,zero])

In [7]:
_pad_1d(input_1d,1)

array([0, 1, 2, 3, 4, 5, 0])

In [19]:
def conv_1d(input_: ndarray, param: ndarray) -> ndarray:
    assert_dim(input_, 1)
    assert_dim(param, 1)
    
    param_len = param.shape[0]
    param_mid = param_len //2
    
    input_pad = _pad_1d(input_,param_mid)
    
    output = np.zeros(input_.shape)
    
    for o in range(output.shape[0]):
        for w in range(param_len):
            output[o] += param[w]*input_pad[o+w]
            
    assert_same_shape(input_,output)
    return output

In [20]:
def conv_1d_sum(input_: ndarray, param: ndarray) -> ndarray:
    output = conv_1d(input_,param)
    return np.sum(output)

In [21]:
conv_1d_sum(input_1d, param_1d)

39.0

In [22]:
conv_1d(input_1d, param_1d)

array([ 3.,  6.,  9., 12.,  9.])

In [25]:
input_1d_2 = np.array([1,2,3,4,6])
param_1d = np.array([1,1,1])

conv_1d_sum(input_1d_2, param_1d)

41.0

In [26]:
def _input_grad_1d(input_: ndarray, param: ndarray, grad: ndarray = None) -> ndarray:
    param_len = param.shape[0]
    param_mid = param_len //2
    
    if grad is None:
        grad = np.ones_like(input_)
    else:
        assert_same_shape(input_, grad)
        
    grad = _pad_1d(grad, param_mid)
    
    input_grad = np.zeros_like(input_)
    
    for i in range(input_grad.shape[0]):
        for p in range(param.shape[0]):
            input_grad[i] += grad[i + param_len -1 - p] * param[p]
            
    assert_same_shape(input_grad, input_)
    
    return input_grad

In [27]:
_input_grad_1d(input_1d, param_1d)

array([2, 3, 3, 3, 2])

In [29]:
input_1d = np.array([1,2,3,4,5])
param_1d_2 = np.array([2,1,1])

print(conv_1d_sum(input_1d, param_1d_2) - conv_1d_sum(input_1d,param_1d))

10.0
